# _*_ coding:utf-8 _*_

"""
File Name : Harvester.py
Author : m0rning
date : 2021-08-05
Description : Process the results generated by theHarvester, add subdomains to OneForAll, need set up file path
"""
from common.query import Query


class Har(Query):
    def __init__(self, domain):
        Query.__init__(self)
        self.domain = domain
        self.module = 'theHarvester'
        self.source = 'theHarvester'
        # 需要修改这个
        self.addr = '/home/kali/Desktop/harvester.txt'

    def query(self):
        """
        向接口查询子域并做子域匹配
        """
        out_flag = 0
        process_flag = 0
        oneforall = set()
        try:
            with open(self.addr, 'r') as f:
                for line in f.readlines():
                    line = line.strip()
                    if '[*] Interesting Urls found:' in line:
                        out_flag = 1
                        # print(line)
                        continue
                    if '[*] Hosts found:' in line:
                        process_flag = 1
                        out_flag = 0
                        continue
                    if out_flag == 1:
                        # print(line)
                    if process_flag == 1 and line == '---------------------':
                        # print(line)
                        continue
                    if process_flag == 1:
                        if ':' in line:
                            host, ip = line.split(':')
                            oneforall.add(host)
                        else:
                            host = line
                            oneforall.add(host)
        except Exception as e:
            print(f'An exception has occurred: {e}')
            return
        self.subdomains.update(oneforall)

    def run(self):
        """
        类执行入口
        """
        self.begin()
        self.query()
        self.finish()
        self.save_json()
        self.gen_result()
        self.save_db()


def run(domain):
    """
    类统一调用入口

    :param str domain: 域名
    """
    query = Har(domain)
    query.run()


if __name__ == '__main__':
    run('baidu.com')
